[package]
name = "micrograd-rs"
version = "0.1.0"
edition = "2024"

[features]
default = ["serde"]
serde = ["dep:byteorder"]

[dependencies]
byteorder = { version = "1.5", optional = true }
rand = "0.9.2"
split-spare = "0.1.0"
